# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bron',
            name='data',
        ),
        migrations.RemoveField(
            model_name='bron',
            name='message',
        ),
        migrations.RemoveField(
            model_name='bron',
            name='number_adult',
        ),
        migrations.RemoveField(
            model_name='bron',
            name='number_kids',
        ),
        migrations.AddField(
            model_name='bron',
            name='phone_number',
            field=models.IntegerField(default='89097552700', max_length=12),
        ),
        migrations.AlterField(
            model_name='bron',
            name='email',
            field=models.EmailField(default='mail@mail.ru', max_length=254),
        ),
        migrations.AlterField(
            model_name='bron',
            name='name',
            field=models.CharField(default='ruslan', max_length=128),
        ),
    ]
